# Copyright (c) 2021 Mert Bora Alper and EASE Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  word-count:
    name: Word Count (FILE Backend)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build driver
        working-directory: driver
        run: make

      - name: Build worker
        working-directory: examples/word-count
        run: make

      - name: Start worker in the background
        working-directory: examples/word-count
        env:
          PORT: 8080
        run: ./bin/word-count &

      - name: Test
        run: ./driver/bin/driver -inputResourceLocator metamorphosis.json > examples/word-count/outputFileName

      - name: Verify
        run: cat $(cat examples/word-count/outputFileName) | LC_ALL=C sort - | cmp examples/word-count/expected-output.tsv -
